import type { Metadata } from "next";
import "./globals.css";
import { getThemeCookies } from "@/actions/theme-cookies";
import { TanstackProvider } from "@/providers/tanstack-provider";
import { FilterContext, FilterContextProvider } from "@/contexts/filter-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = await getThemeCookies();
  return (
    <FilterContextProvider>
      <TanstackProvider>
        <html lang="pt-br">
          <body className={theme}>
            <main>{children}</main>
          </body>
        </html>
      </TanstackProvider>
    </FilterContextProvider>
  );
}
